---
mmdebstrap:
  architectures:
    - arm64
  mode: auto
  keyrings:
    - /usr/share/keyrings/debian-archive-keyring.gpg
  suite: trixie
  variant: standard
  hostname: am62pxx-evm
  components:
    - main
    - contrib
    - non-free-firmware
  packages:
    - build-essential
    - gpg
    - curl
    - firmware-ti-connectivity
    - init
    - iproute2
    - less
    - libdrm-dev
    - libpam-systemd
    - locales
    - net-tools
    - openssh-server
    - sudo
    - vim
    - k3conf
    - weston
    - alsa-utils
    - libasound2-plugins
    - gstreamer1.0-tools
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - i2c-tools
    - linux-image-6.12.13-k3
    - linux-headers-6.12.13-k3
    - linux-libc-dev
    - cryptodev-linux-dkms
    - ti-img-rogue-driver-am62p-dkms
    - ti-img-rogue-firmware-am62p
    - ti-img-rogue-tools-am62p
    - ti-img-rogue-umlibs-am62p
    - firmware-ti-ipc-am62p
    - firmware-cnm-wave
    - libti-rpmsg-char
    - libti-rpmsg-char-dev
    - libd3dadapter9-mesa-dev
    - libd3dadapter9-mesa
    - libegl-mesa0
    - libgbm1
    - libgl1-mesa-dri
    - libglapi-mesa
    - libglx-mesa0
    - libosmesa6
    - mesa-opencl-icd
    - mesa-va-drivers
    - mesa-vdpau-drivers
    - mesa-vulkan-drivers
    - libpru-pssp-dev
    - pru-pssp
    - parted
    - e2fsprogs
    - chromium
    - wpasupplicant
    - seatd
    - cc33xx-target-scripts
    - cc33xx-fw
    - cc33calibrator
    - cc33conf
    - udhcpc
  mirrors:
    - http://deb.debian.org/debian
  setup-hooks:
      # Setup TI Debian Package Repository
    - 'mkdir -p $1/etc/apt/sources.list.d/'
    - 'wget https://raw.githubusercontent.com/TexasInstruments/ti-debpkgs/main/ti-debpkgs.sources -P $1/etc/apt/sources.list.d/'
    - 'sed -i "s/bookworm/trixie/g" $1/etc/apt/sources.list.d/ti-debpkgs.sources'
      # Setup Apt repository preferences
    - 'mkdir -p $1/etc/apt/preferences.d/'
    - 'printf "Package: *\nPin: origin TexasInstruments.github.io\nPin-Priority: 1001" >> $1/etc/apt/preferences.d/ti-debpkgs'
      # Setup Kernel post-install scripts
    - 'mkdir -p $1/etc/kernel/postinst.d/'
    - 'echo "PWD = $PWD"'
    - 'upload target/kernel/postinst.d/cp-kernel-and-overlays /etc/kernel/postinst.d/cp-kernel-and-overlays'
    - 'chmod a+x $1/etc/kernel/postinst.d/cp-kernel-and-overlays'
  essential-hooks:
    # FIXME: Find a better workaround instead of sleep
    - 'sleep 10' # workaround for /proc resource busy unable to umount issue
  customize-hooks:
      # Remove passwd for root user
    - 'chroot "$1" passwd --delete root'
      # Fix apt install mandb permission issue
    - 'chroot "$1" chown -R man: /var/cache/man/'
    - 'chroot "$1" chmod -R 755 /var/cache/man/'
      # update packages to avoid mandatory update after first boot
    - 'chroot "$1" apt-get update'
      # Setup .bashrc for clean command-line experience
    - 'chroot "$1" cp /etc/skel/.bashrc ~/.bashrc'
      # Weston Service and Config Files
    - 'chroot "$1" mkdir -p /etc/systemd/system/'
    - 'upload target/weston/weston.service /etc/systemd/system/weston.service'
    - 'upload target/weston/weston.socket /etc/systemd/system/weston.socket'
    - 'chroot "$1" mkdir -p /etc/default/'
    - 'upload target/weston/weston /etc/default/weston'
    - '$BDEBSTRAP_HOOKS/enable-units "$1" weston'
    - 'chroot "$1" echo "export WAYLAND_DISPLAY=wayland-1" >> $1/etc/profile'
      # systemd-networkd Network Files
    - 'chroot "$1" mkdir -p /etc/systemd/network/'
    - 'upload target/systemd-networkd/10-eth.network /etc/systemd/network/10-eth.network'
    - 'upload target/systemd-networkd/15-eth.network /etc/systemd/network/15-eth.network'
    - 'upload target/systemd-networkd/30-wlan.network /etc/systemd/network/30-wlan.network'
    - 'upload target/systemd-networkd/60-usb.network /etc/systemd/network/60-usb.network'
    - '$BDEBSTRAP_HOOKS/enable-units "$1" systemd-networkd'
      # Enable seatd service
    - '$BDEBSTRAP_HOOKS/enable-units "$1" seatd'
      # Enable ssh to root user without password
    - 'chroot "$1" echo "PermitRootLogin yes" >> $1/etc/ssh/sshd_config'
    - 'chroot "$1" echo "PermitEmptyPasswords yes" >> $1/etc/ssh/sshd_config'
      # Resize Rootfs Service
    - 'chroot "$1" mkdir -p /usr/bin'
    - 'upload target/resize_rootfs/resize_rootfs.sh /usr/bin/resize_rootfs.sh'
    - 'chroot "$1" chmod a+x /usr/bin/resize_rootfs.sh'
    - 'chroot "$1" mkdir -p /etc/systemd/system/'
    - 'upload target/resize_rootfs/resize_rootfs.service /etc/systemd/system/resize_rootfs.service'
    - '$BDEBSTRAP_HOOKS/enable-units "$1" resize_rootfs'

