# This file describes various machine specific settings needed for the build

[am62pxx-evm]
    # device config
    hostname = "am62pxx-evm"
    # u-boot config
    atf_target_board = "lite"
    atf_make_args="K3_PM_SYSTEM_SUSPEND=1"
    optee_platform = "k3-am62x"
    optee_make_args = "CFG_WITH_SOFTWARE_PRNG=y CFG_TEE_CORE_LOG_LEVEL=1"
    uboot_r5_defconfig = "am62px_evm_r5_defconfig"
    uboot_a53_defconfig = "am62px_evm_a53_defconfig"

[am62xx-evm]
    # device config
    hostname = "am62xx-evm"
    # u-boot config
    atf_target_board = "lite"
    atf_make_args="K3_PM_SYSTEM_SUSPEND=1"
    optee_platform = "k3-am62x"
    optee_make_args = "CFG_TEE_CORE_LOG_LEVEL=1"
    uboot_r5_defconfig = "am62x_evm_r5_defconfig"
    uboot_a53_defconfig = "am62x_evm_a53_defconfig"

[am62xx-lp-evm]
    # device config
    hostname = "am62xx-lp-evm"
    # u-boot config
    atf_target_board = "lite"
    atf_make_args="K3_PM_SYSTEM_SUSPEND=1"
    optee_platform = "k3-am62x"
    optee_make_args = "CFG_TEE_CORE_LOG_LEVEL=1"
    uboot_r5_defconfig = "am62x_lpsk_r5_defconfig"
    uboot_a53_defconfig = "am62x_lpsk_a53_defconfig"

[am62xxsip-evm]
    # device config
    hostname = "am62xxsip-evm"
    # u-boot config
    atf_target_board = "lite"
    atf_make_args="K3_PM_SYSTEM_SUSPEND=1"
    optee_platform = "k3-am62x"
    optee_make_args = "CFG_TEE_CORE_LOG_LEVEL=1"
    uboot_r5_defconfig = "am62x_evm_r5_defconfig,am62xsip_sk_r5.config"
    uboot_a53_defconfig = "am62x_evm_a53_defconfig"

[am64xx-evm]
    # device config
    hostname = "am64xx-evm"
    # u-boot config
    atf_target_board = "lite"
    atf_make_args="K3_PM_SYSTEM_SUSPEND=1"
    optee_platform = "k3-am64x"
    optee_make_args = "."
    uboot_r5_defconfig = "am64x_evm_r5_defconfig"
    uboot_a53_defconfig = "am64x_evm_a53_defconfig"
