---
mmdebstrap:
  architectures:
    - arm64
  mode: auto
  keyrings:
    - /usr/share/keyrings/ti-debpkgs.gpg
    - /usr/share/keyrings/debian-archive-keyring.gpg
  suite: bookworm
  variant: standard
  components:
    - main
    - contrib
    - non-free-firmware
  packages:
    - build-essential
    - gpg
    - curl
    - firmware-ti-connectivity
    - init
    - iproute2
    - less
    - libdrm-dev
    - libpam-systemd
    - locales
    - neofetch
    - network-manager
    - net-tools
    - openssh-server
    - sudo
    - vim
    - k3conf
    - alsa-utils
    - libasound2-plugins
    - weston
    - libd3dadapter9-mesa-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libd3dadapter9-mesa=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libegl-mesa0=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libegl1-mesa-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libegl1-mesa=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgbm-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgbm1=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgl1-mesa-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgl1-mesa-dri=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgl1-mesa-glx=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libglapi-mesa=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgles2-mesa-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libgles2-mesa=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libglx-mesa0=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libosmesa6-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libosmesa6=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libwayland-egl1-mesa=22.3.5-1.git20230331.2-0~bookworm+20230420
    - mesa-common-dev=22.3.5-1.git20230331.2-0~bookworm+20230420
    - mesa-opencl-icd=22.3.5-1.git20230331.2-0~bookworm+20230420
    - mesa-va-drivers=22.3.5-1.git20230331.2-0~bookworm+20230420
    - mesa-vdpau-drivers=22.3.5-1.git20230331.2-0~bookworm+20230420
    - mesa-vulkan-drivers=22.3.5-1.git20230331.2-0~bookworm+20230420
    - libpowervr-gl-am62x
    - libti-rpmsg-char-dev
    - libti-rpmsg-char
    - linux-headers-6.1.26
    - linux-image-6.1.26
    - linux-libc-dev
    - wl18xx-ti-utils
  mirrors:
    - http://deb.debian.org/debian
  setup-hooks:
      # Setup TI Debian Package Repository
    - 'mkdir -p $1/usr/share/keyrings'
    - 'curl -s --compressed https://texasinstruments.github.io/ti-debpkgs/KEY.gpg | gpg --dearmor | tee $1/usr/share/keyrings/ti-debpkgs.gpg > /dev/null'
    - 'echo "deb [signed-by=/usr/share/keyrings/ti-debpkgs.gpg] https://texasinstruments.github.io/ti-debpkgs/ ./" > $1/etc/apt/sources.list.d/ti-debpkgs.list'
    - 'mkdir -p $1/etc/kernel/postinst.d/'
    - 'echo "PWD = $PWD"'
    - 'upload target/kernel/postinst.d/cp-kernel-and-overlays /etc/kernel/postinst.d/cp-kernel-and-overlays'
    - 'chmod a+x $1/etc/kernel/postinst.d/cp-kernel-and-overlays'
  essential-hooks:
    # FIXME: Find a better workaround instead of sleep
    - 'sleep 10' # workaround for /proc resource busy unable to umount issue
  customize-hooks:
      # Remove passwd for weston user
    - 'chroot "$1" passwd --delete root'
      # Fix apt install mandb permission issue
    - 'chroot "$1" chown -R man: /var/cache/man/'
    - 'chroot "$1" chmod -R 755 /var/cache/man/'
      # update packages to avoid mandatory update after first boot
    - 'chroot "$1" apt-get update'
      # Setup .bashrc for clean command-line experience
    - 'chroot "$1" cp /etc/skel/.bashrc ~/.bashrc'
      # Weston Service and Config Files
    - 'chroot "$1" mkdir -p /etc/systemd/system/'
    - 'upload target/weston/weston.service /etc/systemd/system/weston.service'
    - 'upload target/weston/weston.socket /etc/systemd/system/weston.socket'
    - 'chroot "$1" mkdir -p /etc/default/'
    - 'upload target/weston/weston /etc/default/weston'
    - '$BDEBSTRAP_HOOKS/enable-units "$1" weston'
